# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: book_message/book.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("book_message/book.proto", :syntax => :proto2) do
    add_message "BookMessage.Book" do
      required :uuid, :string, 1
      required :author, :string, 2
      repeated :title, :string, 3
    end
  end
end

module BookMessage
  Book = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("BookMessage.Book").msgclass
end
